#debug: true

server:
  error:
    whitelabel:
      enabled: false

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/triple?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  sql:
    init:
      encoding: utf-8
      mode: always

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
