CREATE TABLE `USER`
(
    `ID`          BINARY(16) NOT NULL,
    `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE` DATETIME NULL,
    `DISPLAY_ID`  VARCHAR(30) NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE `PLACE`
(
    `ID`          BINARY(16) NOT NULL,
    `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE` DATETIME NULL,
    `ADDRESS`     VARCHAR(200) NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE `REVIEW`
(
    `ID`          BINARY(16) NOT NULL,
    `USER_ID`     BINARY(16) NOT NULL,
    `PLACE_ID`   BINARY(16) NOT NULL,
    `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE` DATETIME NULL,
    `CONTENTS`    longtext ,
    `DELETE_YN`   VARCHAR(1)  DEFAULT 'N',
    PRIMARY KEY (ID)
);

CREATE TABLE `PHOTO`
(
    `ID`                BINARY(16) NOT NULL,
    `REVIEW_ID`         BINARY(16) NOT NULL,
    `ATTACHED_PHOTO_ID` BINARY(16) NOT NULL,
    `CREATE_DATE`       DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`       DATETIME NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE `POINT`
(
    `ID`          BINARY(16) NOT NULL,
    `REVIEW_ID`   BINARY(16) NOT NULL,
    `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE` DATETIME NULL,
    `TYPE`        VARCHAR(10) NULL,
    `DELETE_YN`   VARCHAR(1)  DEFAULT 'N',
    PRIMARY KEY (ID)
);

ALTER TABLE `REVIEW`
    ADD CONSTRAINT `fk_review_user_id` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`);

ALTER TABLE `REVIEW`
    ADD CONSTRAINT `fk_review_place_id` FOREIGN KEY (`PLACE_ID`) REFERENCES `PLACE` (`ID`);

ALTER TABLE `PHOTO`
    ADD CONSTRAINT `fk_photo_review_id` FOREIGN KEY (`REVIEW_ID`) REFERENCES `REVIEW` (`ID`);

ALTER TABLE `POINT`
    ADD CONSTRAINT `fk_point_review_id` FOREIGN KEY (`REVIEW_ID`) REFERENCES `REVIEW` (`ID`);

