CREATE TABLE `REVIEW`
(
    `ID`          BINARY(16) NOT NULL,
    `USER_ID`     BINARY(16) NOT NULL,
    `PLACE_ID`   BINARY(16) NOT NULL,
    `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE` DATETIME NULL,
    `CONTENT`    longtext ,
    `DELETE_YN`   VARCHAR(1)  DEFAULT 'N',
    PRIMARY KEY (ID)
);

CREATE TABLE `PHOTO`
(
    `ID`                BINARY(16) NOT NULL,
    `REVIEW_ID`         BINARY(16) NOT NULL,
    `ATTACHED_PHOTO_ID` BINARY(16) NOT NULL,
    `CREATE_DATE`       DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE`       DATETIME NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE `POINT`
(
    `ID`          BINARY(16) NOT NULL,
    `REVIEW_ID`   BINARY(16) NOT NULL,
    `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_DATE` DATETIME NULL,
    `TYPE`        VARCHAR(20) NULL,
    `DELETE_YN`   VARCHAR(1)  DEFAULT 'N',
    PRIMARY KEY (ID)
);

ALTER TABLE `PHOTO`
    ADD CONSTRAINT `fk_photo_review_id` FOREIGN KEY (`REVIEW_ID`) REFERENCES `REVIEW` (`ID`);

ALTER TABLE `POINT`
    ADD CONSTRAINT `fk_point_review_id` FOREIGN KEY (`REVIEW_ID`) REFERENCES `REVIEW` (`ID`);

create index fk_review_user_id on review (user_id);

create index fk_review_place_id on review (place_id);